title:              TheBranchCut
email:              josorior@uw.edu
description:        Applied Mathematics + Machine Learning.
author:             Felipe Osorio
baseurl:            ""
url:                "https://jfelipeosorio.github.io"

# Social Profiles
twitter_username:   
github_username:    jfelipeosorio
facebook_username:  
instagram_username:  felipeosorior
linkedin_username:  

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

highlighter: rouge